### ISSUE TITLE
Implement SubImaging, SubSegmentation, MultiImaging and MultiSegmentation extractors

### ISSUE THREAD

**Issue by alejoe91** [catalystneuro/roiextractors#11]
@bendichter @Saksham20 
I think that next we have to implement these Extractors:

- SubImagingExtractor: returns a new extractor either cropped in xy or in time
- SubSegmentationExtractor: returns only ROI in a certain square (crops in space)
- MultiImaging and MutiSegmentation --> to handle multiple planes

I think we can use the SI implementations as a reference :)

**Comment by bendichter** [comment]
Sometimes boundaries are not straight. This is supported by e.g. calciumImagingAnalysis [here](https://github.com/bahanonu/calciumImagingAnalysis#removing-cells-not-within-brain-region-with-modelmodifyregionanalysis). Do we want to support that?

**Comment by alejoe91** [comment]
We could for the SegmentationExtractor, but not for the Imaging as retrieving frames and video assumes a rectangular shape

**Comment by bendichter** [comment]
ok, makes sense

**Comment by CodyCBakerPhD** [comment]
All tasks now completed as of #201
