### ISSUE TITLE
Remove special import in `extraction_tools` after dropping python 3.7 support

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/roiextractors#117]
This is a reminder issue. 
For context see the lines added in #116. 

The `hasattr` part in the code above can be removed either when support for Python 3.7 is dropped or the constellations of dependencies allows for using scipy 1.8 in Python 3.7.

Note Python 3.7 will stop receiving security updates in the summer of 2023:
https://peps.python.org/pep-0537/#lifespan

**Comment by bendichter** [comment]
Python version 3.7 end-of-life (EOL) is 27 Jun 2023

**Comment by pauladkisson** [comment]
We no longer support python 3.7, so this should be implemented now right?

**Comment by CodyCBakerPhD** [comment]
I believe what is meant is that `scipy` will _always_ have that attribute post-3.7 minimal compatible version (3.7 would have hard pinned a version prior to inclusion of the submodule)
