### ISSUE TITLE
tests should not all rely on SIMA

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/roiextractors#12]
We should use Numpy Extractors to set up test SegmentationExtractors and ImagingExtractors so that testing each individual interface does not rely on another interface. Relying on SIMA is particularly problematic because it is difficult to install with recent versions of Python. 

See the SpikeExtractors tests for examples of how to do this

**Comment by alejoe91** [comment]
will be fixed here: https://github.com/catalystneuro/roiextractors/pull/48
