### ISSUE TITLE
Unify Memmapable imaging extractors.

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/roiextractors#123]
So, during #112 we seemed to have agreed that we should unify the classes: `NumpyMemmapImagingExtractor` and `Hdf5ImagingExtractor` have them inherit their file processing / reading properties and methods from `MemmapImagingExtractor`. 

@bendichter pointed out that the common handling methods, for example `get_frames()` could use [lazy_ops](https://github.com/catalystneuro/lazy_ops) 

This issue is to keep track of this and discuss something that I might have missed:

To-do:

- [x] Migrate common `write_imaging` method from `NumpyMemmapImagingExtractor` to `MemmapImagingExtractor` #122.
- [ ] Migrate data-handling methods from `NumpyMemmapImagingExtractor` to `MemmapImagingExtractor` while keeping all the previously written tests working. #125 
- [ ] Make the `Hdf5ImagingExtractor` to inherit from `MemmapImagingExtractor` while passing the round-trip tests.

Let me know if I am missing something.

**Comment by CodyCBakerPhD** [comment]
> could use [lazy_ops](https://github.com/catalystneuro/lazy_ops)

Really, *should* use `lazy_ops`, specifically because `h5py.Dataset` objects do not have lazy transpose operations. Also, in the past it has been discovered that certain 'particular' slices of a `np.memmap` can return `np.array`'s instead of `np.memmap`'s, though maybe that has since been fixed.

> Migrate the writing method from Hdf5ImagingExtractor and round-trip tests.

The `Hdf5ImagingExtractor.write_imaging` will still need to exist as-is since that IS a particular file format to HDF5, unlike the binary blob of the `MemmapImaging`. Granted, a sub-portion of that HDF5 file can indeed include a binary blob, but even something as simple as figuring out the byte offset within the file requires `h5py` to infer.

**Comment by h-mayorquin** [comment]
> > could use [lazy_ops](https://github.com/catalystneuro/lazy_ops)
> 
> Really, _should_ use `lazy_ops`, specifically because `h5py.Dataset` objects do not have lazy transpose operations. Also, in the past it has been discovered that certain 'particular' slices of a `np.memmap` can return `np.array`'s instead of `np.memmap`'s, though maybe that has since been fixed.
> 
> > Migrate the writing method from Hdf5ImagingExtractor and round-trip tests.
> 
> The `Hdf5ImagingExtractor.write_imaging` will still need to exist as-is since that IS a particular file format to HDF5, unlike the binary blob of the `MemmapImaging`. Granted, a sub-portion of that HDF5 file can indeed include a binary blob, but even something as simple as figuring out the byte offset within the file requires `h5py` to infer.

So the only methods that `Hdf5ImagingExtractor` will inherit are the data handling ones (such as `get_frames`), then.

**Comment by CodyCBakerPhD** [comment]
> So the only methods that Hdf5ImagingExtractor will inherit are the data handling ones (such as get_frames), then.

Precisely, getting the shape, getting the frames, etc. are all calls that are identical to `np.memmap` objects.

**Comment by h-mayorquin** [comment]
I updated the issue to account for the discussion.

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD no need to do the third point here (make the Hdf5ImagingExtractor to inherit from MemmapImagingExtractor) ? (as per you linked the issue)
