### ISSUE TITLE
Discussion about `get_frame` semantics in ImagingExtractor 

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/roiextractors#155]
This is a follow up on #121 and is meant to be both a summary and a road map of the remaining issues. It should also be useful to align and set priorities. 

For imaging extractors we have in the base class two important methods to interact with the video / data: `get_frames` and `get_video`. In the base class for imaging extractor `get_video` is defined in terms of get frames:

https://github.com/catalystneuro/roiextractors/blob/cd818a22e540060633683fbc6d7d36e39c593dd7/src/roiextractors/imagingextractor.py#L68-L74

So in fact, we only need to agree and give a consistent behavior for `get_frames` across all of our imaging extractors. So, as far as my understanding goes we have come to agree over the following points:

1) When calling `get_frames(frame_idxs=frame_idxs, channel_id=0)` (the default single channel case) the function `get_frames` should return something of the shape `(num_frames, num_rows, num_columns)` except when `frame_idxs` is a scalar where we return something of the shape `(num_rows, num_columns)` (image size). I added a test for this in PR #154 and I think **this is done for all the imaging extractors now.**
2) When calling `get_frames(frame_idxs=frame_dixs, channel_id=None)` (the case for multiple channels) the function `get_frames` should return something of the shame `(num_frames, num_rows, num_columns, num_channels)` except when `frame_idxs` is scalar where it should return something of the shape `(num_rows, num_columns, num_channels)`. This only done for some extractors and we should not support or work into this until the point when we actually get some data that is multi channel. So this is low priority and should be done for later. Meanwhile, @CodyCBakerPhD has standarized and added errors to most (hopefully all?) of these cases #149

I also think that the tests added in PR #154 make the recently added tests redundant:
https://github.com/catalystneuro/roiextractors/blob/cd818a22e540060633683fbc6d7d36e39c593dd7/tests/test_io.py#L80-L89

Maybe I am missing something, my feeling is that at least for imaging extractors we will be done with standardization after closing PR #154 .

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD 
`get_frame` should never squeeze the frame axis (or the rows and columns as we don't have an API to cut over them). All the other dimensions such as channel or depth are to be squeezed if they are specified. 

We both agree that we should support the simplest possible API. I think the semantics of this should be the ones of [slicing](https://docs.python.org/3/library/functions.html#slice) in python (possible without step). Moreover, I think we should not support numpy type [indexing](https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing) (otherwise known as advanced indexing or fancy indexing) as this is complicated to test and we don't really use that functionality.

We can implementing averages by allowing step into slicing. `get_traces` in `spikeinterface` uses slicing semantics but does not support step.

**Comment by h-mayorquin** [comment]
`get_traces` signature in `spikeinterface`:

https://github.com/SpikeInterface/spikeinterface/blob/f65c301c985d0fe7ae9ff32c38bff8914d4e9be9/spikeinterface/core/baserecording.py#L94-L101

**Comment by CodyCBakerPhD** [comment]
>  NWB conversion tools should be changed to use get_video instead of get_frames.

This part is also already in progress with https://github.com/catalystneuro/nwb-conversion-tools/pull/575

**Comment by h-mayorquin** [comment]
I just went through the state of the tests and I think we covered most cases. Plus, now everything is centered around `get_video` and this discussion looks less relevant now. I am closing this, if a problem along this lines comes is better to handle it in a new issue.

Thanks for @CodyCBakerPhD as I remember it took us quite a while to get consensus on this.
