### ISSUE TITLE
Add a documentation section about the standard format for `get_frames`

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/roiextractors#156]
As described in the title. When finish agreeing over final details in  #155.

Quoting @CodyCBakerPhD 
> For example, this tutorial for EXTRACT https://github.com/schnitzer-lab/EXTRACT-public/blob/master/Learning%20materials/Lecture%20Tutorials/Tutorial%201%20-%20Starting%20code/example_tutorial.m

> indicates the data storage as height x width, which we as rows x cols (https://github.com/catalystneuro/roiextractors/blob/master/src/roiextractors/extractors/schnitzerextractor/extractsegmentationextractor.py#L131, though not terribly obvious to read from that code, also not very educational since the example data is square...) but then this will get transposed to NWB standard, which is width x height... It can get very confusing and it would be great to have a nicely documented showcase for it

**Comment by pauladkisson** [comment]
Fixed by #244
