### ISSUE TITLE
hdf5 dataset reader

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/roiextractors#173]
https://github.com/catalystneuro/roiextractors/blob/57b5305dfb1cbcb2c12fa01ed9565ebeb556044e/src/roiextractors/extractors/hdf5imagingextractor/hdf5imagingextractor.py#L103

why use lazy_ops and then read the data? This line should simply be 

```python
frames = self._video[:, :, :, channel]
```

**Comment by bendichter** [comment]
@h-mayorquin

**Comment by h-mayorquin** [comment]
That was needed for it to work with nwb conversion tools functionality. Something with the `add_two_photon_series` functionality required the output of get frames to be a numpy array. I will double check it the week after.

**Comment by h-mayorquin** [comment]
Ok, I tested the linked branch (#174) against `nwb conversion tools` and it seems to work but there are some errors there discussed in the pull request.
