### ISSUE TITLE
Floats comparison on numpy array requieres `assert_allclose`

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/roiextractors#193]
Hey guys @CodyCBakerPhD @weiglszonja 

You went ahead with the merge on #190 without address my comments here:
https://github.com/catalystneuro/roiextractors/pull/190#discussion_r944526026

Whereas I don't think this is a super-critical issue I don't really understand your thought process and I would like to sort this out:

As you must be aware comparing floating for equality is [not trivial. ](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html)For testing,  numpy provides https://numpy.org/doc/stable/reference/routines.testing.html of which you were using `assert_all_equal`. I was arguing that when you want to compare floats you need to use `numpy.testing.assert_almost_equal` (which after checking the documentation I have learned that numpy now endorses `numpy.test_assert_allclose`).

My claim is that using `assert_all_equal` leads to false positive for assertions which is illustrated with examples as simple as this:

```python
In [1]: import numpy as np

In [2]: x = np.random.rand(10, 10)

In [3]: np.testing.assert_array_equal((1e6 * x) * 1e-6, x)
```
This throws an assertion. 
Whereas this does not:
```python
np.testing.assert_allclose((1e6 * x) * 1e-6, x)
```

@CodyCBakerPhD  argues that it might be useful to know when errors like this happens and which I can't understand either. Bear in mind that in `neuroconv` we use this to compare the extractors to the their versions when extracted after writing an `nwbfile` through the `NwbSegmentationExtractor` which might lead to drift in float representation. I don't really understand why you don't want to use the numpy sanctioned way to compare floats.

**Comment by CodyCBakerPhD** [comment]
I'm aware of errors from floating point arithmetic, and how to adjust tests for them.

The tests in question are not applied to the results of any arithmetic, they apply directly to stored and retrieved data. Basically, checking that bytes in equals bytes out, but done at the level of converting the bytes to a data array since humans can actually read that and it represents how people would actually use the API.

If there any byte loss or bit-wise differences for such data access methods, that would be useful to know.

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD 
> Basically, checking that bytes in equals bytes out, but done at the level of converting the bytes to a data array since humans can actually read that and it represents how people would actually use the API.
I don't understand what do you mean by "it represents how people would actually use the API"

I think that if what you really want is to "test that the float representation of the loaded numpy array is the EXACTLY the same"  then that's fine and I get you. That's probably a strict test that applies well to the input-output tests that we have were we write and read immediately with the same format and then compare (I mean the stuff in `test_io.py`). However, if you want to use this function more generally (as in comparing objects that are meant to be equal but loaded from different formats the way that we do in our tests in `neuroconv`) then the specific representation matters less as the data might be loaded from other formats (nwb, json for provenance as it is done in `spikeinterface`, etc) and then it is unlikely that the representation is EXACTLY the same. 

If I am guessing well and I understood you correctly, you think that the former is more important than the second and that explains your position. My take in that case is that if you really want to go that road I think that we should use the principle of [separations of concerns ](https://en.wikipedia.org/wiki/Separation_of_concerns) and create two tests, 1) that tests equal byte representation and 2) tests for image equality. While this is not a critical issue and therefore has low priority it is important to keep conceptual clarity that we are testing for two things with one statement and we can encode intent better.
