### ISSUE TITLE
Suite2pSegmentationExtractor still uses (num_rois, num_frames) format for its traces

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/roiextractors#206]
We have changed this in #200 but the following code still raises an error

```python
folder_path=str(OPHYS_DATA_PATH / "segmentation_datasets" / "suite2p")
extractor = Suite2pSegmentationExtractor(folder_path=folder_path)

assert extractor.get_traces(name="raw").shape == (extractor.get_num_frames(),extractor.get_num_rois())
```

More concretely:
```
extractor.get_num_frames(), extractor.get_num_rois(), extractor.get_traces(name="raw").shape
(250, 15, (15, 250))
```

**Comment by h-mayorquin** [comment]
Importantly the similar test that @CodyCBakerPhD  is running in #207 does not fail:

```
assert extractor.get_traces_dict()["raw"].shape == (extractor.get_num_frames(),extractor.get_num_rois())
```

**Comment by CodyCBakerPhD** [comment]
OK I can reproduce it now. I agree this is very confusing how this delivers conflicting behavior, and we should probably only have one function for retrieving traces (and probably another function altogether for specifying what traces are instantiated in a given extractor)
