### ISSUE TITLE
[Feature]: Allow for incomplete data ingestion

### ISSUE THREAD

**Issue by RichieHakim** [catalystneuro/roiextractors#224]
### What would you like to see added to nwb-conversion-tools?

I would like to use `roiextractors` as a bridge for ingesting data from multiple data sources in a package I am working on ([https://github.com/RichieHakim/ROICaT](https://github.com/RichieHakim/ROICaT)). 

Ttime series fluorescence fluorescence is not necessary for my pipeline to work. For example, for Suite2p output data, I only ingest the stat.npy and ops.npy files and nothing else. Given the large size of the F.npy and similar files compared to the small size of stat.npy and ops.npy, it would be advantageous to allow the roiextractors classes to allow for incomplete data ingestion, i.e. importing directories containing only stat.npy and ops.npy files but not F.npy etc.

### What solution would you like?

Allow for incomplete data ingestion. If traces are missing, only throw a warning, not an error. Perhaps provide an argument like `allow_incomplete_data`.

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/roiextractors/blob/master/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/roiextractors/issues)?

**Comment by bendichter** [comment]
@RichieHakim nice to meet you! It's very cool that you want to use ROI Extractors for this. So far we have only used it as an ingestion tool for NeuroConv, but it is intended to be general-purpose and you tool looks like a great alternative use-case. And of course it would be great to get a small community together so we can benefit from each other's work in API standardization. In principle, I think your request is reasonable, but if course the devil is in the details. @h-mayorquin , what do you think? How difficult would it be to implement something like this?

**Comment by h-mayorquin** [comment]
I took a look at this. I think it would be straighforward.  We already have in our dummy segmentation extractor (for testing purposes) functionality for not loading the diverse traces:

https://github.com/catalystneuro/roiextractors/blob/062f69ee97b6052917be63d1a971e2a8229e8808/src/roiextractors/testing.py#L54-L67

**Comment by RichieHakim** [comment]
I wrote a PR related to this: https://github.com/catalystneuro/roiextractors/pull/227
However, I noticed that the other ingestion classes don't all properly ingest all of the data I would need. These include only two things: roi_masks and FOV_images (like a mean FOV image or 'sample image'). It seems like 

For example with `CaimanSegmentationExtractor` it seems like it only attempts to ingest a 'correlation image' if a field (['estimators']['Cn']) is present. Otherwise it gives up. In the example date you have, it does not find this field. See below:
https://github.com/catalystneuro/roiextractors/blob/062f69ee97b6052917be63d1a971e2a8229e8808/src/roiextractors/extractors/caiman/caimansegmentationextractor.py#L51
https://github.com/catalystneuro/roiextractors/blob/062f69ee97b6052917be63d1a971e2a8229e8808/src/roiextractors/extractors/caiman/caimansegmentationextractor.py#L78

Is it possible to make this more robust? It seems like this may be the case with the other extractors as well. I do not have experience with other extraction methods, nor do I have example output files from different pipelines beyond the ones you provide in the gin repo.

**Comment by CodyCBakerPhD** [comment]
@RichieHakim Sorry for the delayed response on this

We spoke about it at our group meeting and decided the simplest course of action for now would be to guarantee completely lazy reading for all extractors, which ought to be trivial and we were quite surprised it wasn't already implemented across the board on ROIExtractors. We'll try to get that in place soon

The long-term desired API would be to introduce the notion of a 'stream' to ROIExtractors, analogous to the [NEO](https://github.com/NeuralEnsemble/python-neo) and [SpikeInterface](https://github.com/SpikeInterface/spikeinterface/blob/main/doc/index.rst) projects in the extracellular electrophysiology sector; for SegmentationExtractors, each stream would be a different ROI response series and a single extractor would correspond one-to-one with each series for simplicity, which grants the level of granularity requests in this original issue
