### ISSUE TITLE
[Feature]: Notify admins on daily test failure

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/roiextractors#266]
### What would you like to see added to ROI Extractors?

I haven't been getting the regular notifications of failure from daily tests here

Would be great to use the email notifier used on other projects in our ecosystem: https://github.com/catalystneuro/neuroconv/blob/c39dbb101f5c16b7a2d3ff11f6a8be6287c459ae/.github/workflows/dailies.yml#L20C1-L34C161

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/roiextractors/blob/master/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/roiextractors/issues)?

**Comment by pauladkisson** [comment]
Fixed by #320
