### ISSUE TITLE
move bioformats because it is GPL

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/roiextractors#27]
We want to license RoiExtractors as open-permissive, but Bio-formats is GPL. @alejoe91, RoiExtractors cannot import Bio-Formats. Can you move all bio-format-related content to an entirely new repository? Maybe we can call it RoiExtarctors-GPL, to make the association clear. Code in RoiExtarctors-GPL can depend on RoiExtractors and import any necessary base classes. We just need to make a very clear delineation between code that depends on GPL libraries and code that does not.

**Comment by alejoe91** [comment]
Sure!

**Comment by alejoe91** [comment]
https://github.com/catalystneuro/roiextractors/pull/42

moved to: https://github.com/catalystneuro/roiextractors-gpl
