### ISSUE TITLE
Discussion: attrs vs dicts

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/roiextractors#35]
I would like to discuss where it would be more appropriate to store variables as attributes directly in the class e.g: 

```python
self._fluorescence= ...
self._neuropil_response = ...
```
vs. a dictionary, e.g.:

https://github.com/catalystneuro/roiextractors/blob/4e5117ecabcb2340ca72166e32db96d411add351/roiextractors/extractors/suite2p/suite2psegmentationextractor.py#L38-L40

This has come up twice in `SegmentationExtractors`: in the `self._roi_response_dict` as shown above, and again with summary images:

https://github.com/catalystneuro/roiextractors/blob/4e5117ecabcb2340ca72166e32db96d411add351/roiextractors/extractors/suite2p/suite2psegmentationextractor.py#L124-L136

In my opinion, I would prefer direct attributes of the class in cases like these where we desire uniform naming across processing systems. The main advantage is that it more directly encourages/enforces that we use the same internal naming convention across extractors. This is necessary if we want to be able to save a summary image from one processing system and load it into another. For instance, the correlation in suite2p is called Vcorr, and the correlation image in CaImAn is called Cn. If we keep their original names, and try to convert suite2p into CaImAn for use in the CaImAn GUI, their system will not be able to find the correlation image by the name they expect.

We can enforce specific names by setting this variables to `None` in `SegmentationExtractor.__init__`, so it is clear what the names should be. We should probably also document each of these, at least with inline comments, so that contributors understand what each one means.

I can see why the dictionary is appealing. First of all, it neatly organizes all of the variables that have the same basic form (all are responses over time, or all are summary images). It also allows a user to add a new type of response-over-time, or summary-image that we have not built in yet. Another pattern that would allow us to continue to have these features would be to have new attributes that store a list of the names of all the attributes of this type, e.g.

```python
self.responses_over_time = ['fluorescence', 'neuropil', 'deconvolved']
```
and then if you needed a dict you could construct it on the fly:
```python
{label: segext.get(label) for label in segext.responses_over_time}
```

The user can also add a new attribute, e.g.

```python
self.gauss_blur_image = ...
self.summary_images.append('gauss_blur_image')
```

**Comment by Saksham20** [comment]
I have made an initial implementation just for the caiman extractor here 8d14fecd7902d7d17e390c322dffe768ea4d5b8f

@bendichter How do we intend to enforce naming conventions if we give the user the option to add new attribute?
