### ISSUE TITLE
unused variables in NwbSegExt

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/roiextractors#6]
These variables are unused

https://github.com/catalystneuro/segmentationextractors/blob/ccbdd3146be1565b16974c668f1deb591296dcbe/segmentationextractors/nwbextractor/nwbsegmentationextractor.py#L78-L82

**Comment by Saksham20** [comment]
fixed here : 0cdcb4329d52adbc6c704f3c6290d096348a022d
