### ISSUE TITLE
image_masks vs pixel_masks as default storage in nwb

### ISSUE THREAD

**Issue by Saksham20** [catalystneuro/roiextractors#71]
What would be a better way of storing roi data: `pixel_masks `vs `image_masks`?.
 I can think of 2 criteria: **storage vs computational efficiency**. I think this is an important consideration especially now since we're churning through large datasets like from Giocomo Lab. 

**Storage**: `pixel_masks `are way better since they're sparse. In case of a dataset from the GIocomo Lab: **pixel masks are 2.95MB vs image masks take 5.63 GB**! due to the small ROI sizes Thus writing the `SegmentationExtractor `to nwb is high on storage and conversion rate much slower. 
**Computational**: any downstream analysis would require to do the computationally step of sparse to normal array conversion

What do you guys think?

**Comment by alejoe91** [comment]
HI @Saksham20 

From pixel masks one can always make image_masks. IMO pixel mask is a better representation and I don't think that making an image_mask out of a pixel mask would be too computationally intense for any downstream analysis.

**Comment by bendichter** [comment]
@Saksham20 have you tried compressing image masks? they might be even smaller than pixel masks when compressed. But I agree that allowing the API to output either on the fly would be fine

**Comment by Saksham20** [comment]
> @Saksham20 have you tried compressing image masks? they might be even smaller than pixel masks when compressed. But I agree that allowing the API to output either on the fly would be fine

Yes, compression helps alot: factor of **789:1**, so the nwbfile with image_masks is **5.63>7.13MB** .
Storage problem is solved, but when calling segext.get_image_masks() prior to writing, it **loads the full dataset all into memory.** 

In this case it would be better to store pixel_masks. So, what I'm thinking:

1. Either we do this for all extractors. So `write_segmentation()` writes pixel_mask to nwb by default.
2. Have each class define a internal attr (`self._image_mask_exist=True/False`, `self._pixel_mask_exist=T/F`) which states what the default storage format in the sgementation file(**caiman.h5**: `image_mask`, **extract.mat**: `image_mask`, **suite2p**: `pixel_mask`),
3. The nwb write segmentation checks this to decide what to write by default.

**Comment by Saksham20** [comment]
The other option is to use [DataChunkIterator](https://hdmf.readthedocs.io/en/stable/hdmf.data_utils.html#hdmf.data_utils.DataChunkIterator) for buffered read.
But this is throwing some errors: #74
