### ISSUE TITLE
output from ImagingExtractor.get_image_size leads to failing metadata validation in nwb_conversion_tools

### ISSUE THREAD

**Issue by cechava** [catalystneuro/roiextractors#84]
output is a numpy array. Validation expects a python list

**Comment by CodyCBakerPhD** [comment]
I wouldn't say this is a bug on `roiextractors` per se; as an API of itself, it's probably better for it to return things as the more general `np.ndarray`, which supports richer types of operations than a standard list does. The validation this is related to pertains to a specific JSON schema on another repo (`nwb-conversion-tools`) that uses some of the functions from this API in specific ways that differ from typical use.

**Comment by cechava** [comment]
will make a fix on the nwb-conversion-tools side
